### ISSUE TITLE
Issue with `pytorch-lightning` version 1.7.5 and `torchmetrics` version 0.9.3 on Sherlock

### ISSUE THREAD

**Issue by TianyuDu** [gsbDBI/bemb#13]
I am reporting the issue identified by Rachel @rachelyangzhou please see below for the error message.
The package works with version 1.4.5

## Issue 1
```
>>> import bemb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/bemb/__init__.py", line 2, in <module>
    import bemb.model
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/bemb/model/__init__.py", line 2, in <module>
    from .bemb_flex_lightning import *
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/bemb/model/bemb_flex_lightning.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/core/__init__.py", line 15, in <module>
    from pytorch_lightning.core.datamodule import LightningDataModule
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/core/datamodule.py", line 21, in <module>
    from pytorch_lightning.core.mixins import HyperparametersMixin
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/core/mixins/__init__.py", line 15, in <module>
    from pytorch_lightning.core.mixins.device_dtype_mixin import DeviceDtypeModuleMixin  # noqa: F401
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 19, in <module>
    from typing_extensions import Self
ImportError: cannot import name 'Self' from 'typing_extensions' (/share/software/user/open/py-pytorch/1.8.1_py39/lib/python3.9/site-packages/typing_extensions.py)
```

## Issue 2
There is also an issue with the latest `torchmetric` version 0.9.3, rolling back to version `0.6.0` solves the issue.

Please see below for the error message.
```
>>> import bemb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/bemb/__init__.py", line 2, in <module>
    import bemb.model
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/bemb/model/__init__.py", line 2, in <module>
    from .bemb_flex_lightning import *
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/bemb/model/bemb_flex_lightning.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/home/users/zhoury/.local/lib/python3.9/site-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/home/users/zhoury/.local/lib/python3.9/site-packages/torchmetrics/utilities/data.py)
```

**Comment by TianyuDu** [comment]
I have created a new document [here](https://github.com/gsbDBI/bemb/wiki/Deployment-on-Sherlock-(Updated,-with-Virtual-Environment)) of procedure to install our own PyTorch instead of loading the PyTorch module on sherlock. This simplifies the deployment and makes everything easier.
